=== giellalt/dict-nob-sme/dtd/nobsme.dtd
<!ELEMENT r ( lics? , e+ ) >
<!ATTLIST r
xml:lang ( nob ) #IMPLIED
id ( nobsme ) #IMPLIED 
>
<!ELEMENT lics  ( lic , ref* , sourcenote* )>
<!ATTLIST lics xml:space (default|preserve) 'preserve'
          xmlns:xhtml CDATA #FIXED "http://www.w3.org/1999/xhtml"
          xhtml:script CDATA "http://www.w3.org/1999/xhtml"
          >

<!ELEMENT lic (#PCDATA|a)*>
<!ATTLIST lic xml:lang ( en | nno ) #IMPLIED >
<!ELEMENT ref (#PCDATA|a|i)*>
<!ELEMENT sourcenote (#PCDATA|a)*>
<!ELEMENT a (#PCDATA)>

<!ELEMENT e  ( lg, mg+, ig* )>
<!ATTLIST e
src CDATA #IMPLIED
note CDATA #IMPLIED
>

<!ELEMENT lg  ( l )>

<!ELEMENT l  ( #PCDATA )>
<!ATTLIST l
pos ( A | Abbr | Adv | CC | CS | Interj |
      N | Num | Po | Pr | Pron | V | Det ) #IMPLIED
alt_str CDATA #IMPLIED
nr ( Pl ) #IMPLIED
type ( Prop | Indef | Recipr | Pers | Refl | Dem | Poss | Rel | Interr | Qnt ) #IMPLIED 
orig_entry CDATA #IMPLIED
til_ref CDATA #IMPLIED
t_type (phrase) #IMPLIED
src CDATA #IMPLIED
>

<!ELEMENT mg  ( l_ref?, re? , tg+ )>

<!ELEMENT l_ref  ( #PCDATA )>

<!ELEMENT ig ( i, id?, it+)+ >
<!ELEMENT i (#PCDATA) >
<!ELEMENT id (#PCDATA) >
<!ELEMENT it (#PCDATA) >
<!ATTLIST it src CDATA #IMPLIED >


<!ELEMENT tg  ( re? , t+ , xg* )>
<!ATTLIST tg xml:lang ( sme ) #REQUIRED >


<!ELEMENT re  ( #PCDATA )>
<!ATTLIST re
fra_ref CDATA #IMPLIED
>

<!ELEMENT t  ( #PCDATA )>
<!ATTLIST t
pos ( A | N | V | Adv | Po | Pr | Pron | Rel |  Det | Interj | Pcle |
            Num | CC | CS | fp-cmp ) #IMPLIED
t_type ( expl | grammarexpl | phrase | grammar ) #IMPLIED  
src CDATA #IMPLIED
type ( NomAg | G3 | G7 | Prfprc | Prsprc | Indef | Rel | Refl | Recipr | Interr | Pers | Dem | Prop ) #IMPLIED
alt_str CDATA #IMPLIED
nr ( Sg | Du | Pl ) #IMPLIED
dial ( east | west | torne | varanger ) #IMPLIED
href CDATA #IMPLIED
reg CDATA #IMPLIED 
>

<!ELEMENT xg  ( re? , x , xt* )>

<!ELEMENT x  ( #PCDATA )>
<!ATTLIST x
src CDATA #IMPLIED
>

<!ELEMENT xt  ( #PCDATA )>
<!ATTLIST xt
src CDATA #IMPLIED
>

=== giellalt/dict-nob-sme/src/CS_static_nobsme.xml
<?xml version='1.0' encoding='UTF-8'?>
<!DOCTYPE r PUBLIC "-//DivvunGiellatekno//DTD Dictionaries//Multilingual" "../dtd/nobsme.dtd">
<r id="nobsme" xml:lang="nob">
   <e>
      <lg>
         <l pos="CS">som</l>
      </lg>
      <mg>
         <tg xml:lang="sme" tw_id="som 7dfa5b93-b9e7-4ff1-91a5-9e6fafa6c2bd">
            <t pos="CS">mii</t>
            <xg>
               <x>Det som skjer, det skjer.</x>
               <xt>Dat mii dáhpáhuvvá, dat dáhpáhuvvá.</xt>
            </xg>
            <xg>
               <x>Máret tenkte på banklånet som hun skulle betale i dag.</x>
               <xt>Máret jurddašii báŋkoloana birra maid galggai máksit odne.</xt>
            </xg>
            <xg>
               <x>Jeg hentet den motoren som Niillas hadde reparert.</x>
               <xt>Vižžen mutuvrra, man Niillas lei divvon.</xt>
            </xg>
            <xg>
               <x>Søknader som kommer etter den tidsfristen, behandles ikke.</x>
               <xt>Ohcamat mat bohtet dan áigemeari maŋŋel, eai meannuduvvo.</xt>
            </xg>
         </tg>
      </mg>
      <mg>
         <tg xml:lang="sme" tw_id="som 428fe084-b4cd-458e-96a5-e6762484a862">
            <re>om mennesker</re>
            <t pos="CS">gii</t>
            <xg>
               <x>I gamle dager var det en fattig mann som ofte var innom og tigget hos presten.</x>
               <xt>Dološ áigge lei muhtin geafes olmmái gii dávjá finadii báhpa luhtte ánuheame.</xt>
            </xg>
            <xg>
               <x>Áššu snakket med mange som ikke var fornøyde.</x>
               <xt>Áššu humadii máŋgasiin geat eai lean duhtavaččat.</xt>
            </xg>
            <xg>
               <x>Der er det fem fotballspillere som Reisa vil på laget.</x>
               <xt>Doppe leat vihtta čiekči geaid Ráisa háliida iežaset jovkui.</xt>
            </xg>
            <xg>
               <x>Våre fotballspillere har sagt hvem de ønsker som trener.</x>
               <xt>Min spábbačiekčit leat lohkan gean sii háliidit hárjeheaddjin.</xt>
            </xg>
         </tg>
      </mg>
      <mg>
         <tg xml:lang="sme" tw_id="som 812937de-ec4a-47dd-b2e2-e3c7b51ab229">
            <re>innenfor en avgrenset gruppe</re>
            <t pos="Pron" type="Interr">guhte</t>
            <xg>
               <x>Elle fortalte hva hver enkelt tok.</x>
               <xt>Elle muitalii maid guhte válddii.</xt>
            </xg>
            <xg>
               <x>Kursene er ment for dem som kan litt samisk fra før.</x>
               <xt>Kurssat leat sin várás guđet máhttet veaháš sámegiela ovddežis.</xt>
            </xg>
         </tg>
      </mg>
      <mg>
         <tg xml:lang="sme" tw_id="som 2909d2f0-80ab-407d-84f6-66413f30f16a">
            <t pos="CS">go</t>
            <xg>
               <x>For dem er samisk et fremmedspråk, som de må begynne å lære på samme måte som andre fremmedspråk.</x>
               <xt>Sidjiide lea sámegiella amas giella, maid fertejit oahppagoahtit seammá láhkai go eará amas gielaid.</xt>
            </xg>
            <xg>
               <x>Ta en slik som du vil ha.</x>
               <xt>Váldde dakkára go áiggut.</xt>
            </xg>
         </tg>
      </mg>
      <mg>
         <tg xml:lang="sme" tw_id="som f3daf4a1-f614-45f5-894f-82b839bab012">
            <t pos="CS">nugo</t>
            <xg>
               <x>Gjør som jeg.</x>
               <xt>Daga nugo mun.</xt>
            </xg>
            <xg>
               <x>Sier du det?</x>
               <xt>Nugo?</xt>
            </xg>
            <xg>
               <x>Dagens nyhetsformidlere kan ikke fortelle nyheter engang slik som de pleide å gjøre i gamle dager.</x>
               <xt>Dán áigásaš ođasmuitaleaddjit eai máhte ságaidge muitalit nugo dolin lávejedje.</xt>
            </xg>
            <xg>
               <x>På isen var det også små underholdningsinnslag, slik som skallekasting.</x>
               <xt>Jieŋa alde ledje maid smávva suohtastallamat, nugo gámabálkesteapmi.</xt>
            </xg>
         </tg>
      </mg>
      <mg>
         <tg xml:lang="sme" tw_id="som 069a3c1d-f602-4f2c-893f-501c29c38152">
            <t pos="Pron" type="Rel">guhten</t>
            <xg>
               <x>Den filmstjerna som du har lyst til å bli, er satt i fengsel.</x>
               <xt>Dat filbmanásti, guhten don háliidivččet šaddat, lea biddjon giddagassii.</xt>
            </xg>
         </tg>
      </mg>
      <mg>
         <tg xml:lang="sme" tw_id="som 425fc85a-35a2-482a-a4f7-c444334eebdc">
            <t pos="Pron" type="Rel">guđiid</t>
            <xg>
               <x>De klærne, som jeg nettopp har vasket, må vaskes igjen.</x>
               <xt>Daid biktasiid, guđiid mun lean aiddo bassan, ferte fas bassat.</xt>
            </xg>
         </tg>
      </mg>
      <mg>
         <tg xml:lang="sme" tw_id="som c665586c-3666-4c57-a99c-b253c6bc01db">
            <t pos="Pron" type="Rel">guđiide</t>
            <xg>
               <x>Til de husene, som du leverte julegaver til, er det allerede kommet julebesøk.</x>
               <xt>Daidda viesuide, guđiide don dolvot juovlaskeaŋkkaid, leat jo boahtán juovlaguossit.</xt>
            </xg>
         </tg>
      </mg>
      <mg>
         <tg xml:lang="sme" tw_id="som bb12ca4f-e479-4cdd-be9e-42bd6d94548b">
            <t nr="Pl" pos="Pron" type="Rel">guđiin</t>
            <xg>
               <x>De husene som har garasjer, er dyre.</x>
               <xt>Dat viesut, guđiin leat biilavisttit, leat divrasat.</xt>
            </xg>
         </tg>
      </mg>
      <mg>
         <tg xml:lang="sme" tw_id="som b31789c2-9d4a-4322-a15e-74bdef5ba97f">
            <t pos="Pron" type="Rel">guđiiguin</t>
            <xg>
               <x>Med de maskinene som det er lettest å sy med, er det alltid noen som syr.</x>
               <xt>Daiguin mašiinnaiguin, guđiiguin lea álkimus goarrut, leat álo olbmot goarrume.</xt>
            </xg>
         </tg>
      </mg>
   </e>
</r>

=== giellalt/dict-nob-sme/src/CC_nobsme.xml
<?xml version='1.0' encoding='UTF-8'?>
<!DOCTYPE r PUBLIC "-//DivvunGiellatekno//DTD Dictionaries//Multilingual" "../dtd/nobsme.dtd">
<r id="nobsme" xml:lang="nob">
   <e>
      <lg>
         <l pos="CC">eller</l>
      </lg>
      <mg>
         <tg xml:lang="sme" tw_id="eller f01ac27d-b69f-4ab3-9287-ae0aa9edb3d5">
            <re>i fortellende setninger</re>
            <t pos="CC">dahje</t>
            <t pos="CC">dahjege</t>
            <xg>
               <x>Alle hadde funnet klær eller andre ting som de ville kjøpe.</x>
               <xt>Buohkat ledje gávdnan biktasiid dahje eará dávviriid maid háliidedje oastit.</xt>
            </xg>
         </tg>
      </mg>
      <mg>
         <tg>
            <re>i spørsmålssetninger med flere enn to alternativer</re>
            <t pos="CC">dahje</t>
            <xg>
               <x>Trenger du veiledning eller hjelp?</x>
               <xt>Dárbbašat go bagadusa dahje veahki?</xt>
            </xg>
         </tg>
      </mg>
      <mg>
         <tg xml:lang="sme" tw_id="eller d5507b9e-9221-4d97-8d7c-9e2378673077">
            <re>i spørsmålssetninger med bare to alternativer</re>
            <t pos="CC">vai</t>
            <xg>
               <x>Er du den som skal komme, eller skal vi vente på en annen?</x>
               <xt>Leat go don dat guhte galgá boahtit, vai galgat go vuordit muhtun eará?</xt>
            </xg>
            <xg>
               <x>Vil du ha kaffe eller te?</x>
               <xt>Siđat go gáfe vai deaja?</xt>
            </xg>
         </tg>
      </mg>
   </e>
   <e>
      <lg>
         <l pos="CC">og</l>
      </lg>
      <mg>
         <tg xml:lang="sme" tw_id="og 3e8841f7-68ab-47f3-8988-67a7eefdb1ac">
            <t pos="CC">ja</t>
            <xg>
               <x>Det er både bra og dårlig.</x>
               <xt>Dat lea sihke buorre ja heittot.</xt>
            </xg>
         </tg>
      </mg>
      <mg>
         <tg xml:lang="sme" tw_id="og 36600f04-0886-498c-b32a-84b62fb29746">
            <re>mellom identiske komparativformer</re>
            <t pos="CC">ahte</t>
            <xg>
               <x>mer og mer</x>
               <xt>eanet ahte eanet</xt>
            </xg>
            <xg>
               <x>Penger blir viktigere og viktigere.</x>
               <xt>Ruhta šaddá deaŧalaččat ahte deaŧalaččat.</xt>
            </xg>
         </tg>
      </mg>
   </e>
   <e>
      <lg>
         <l pos="CC">samt</l>
      </lg>
      <mg>
         <tg xml:lang="sme" tw_id="samt 8373d8f5-9dc6-4f9d-bf25-5781e2ac704a">
            <t pos="CC">ja maid</t>
            <xg>
               <x>Beskjeden kom pr. mail samt pr. telefon?</x>
               <xt>Diehtu bođii maila bokte, ja maid telefovnna bokte.</xt>
            </xg>
         </tg>
      </mg>
   </e>
   <e>
      <lg>
         <l pos="CC">men</l>
      </lg>
      <mg>
         <tg xml:lang="sme" tw_id="men ac730f6e-ea97-4423-8729-5c2557b6befd">
            <t pos="CC">muhto</t>
            <xg>
               <x>Jeg kan godt hjelpe deg, men i dag har jeg ikke tid.</x>
               <xt>Mun sáhtán áinnas veahkehit du, muhto odne in astta.</xt>
            </xg>
         </tg>
      </mg>
   </e>
</r>

=== giellalt/dict-nob-sme/src/Po_nobsme.xml
<?xml version='1.0' encoding='UTF-8'?>
<?xml-stylesheet media="screen"              title="Dictionary view"   href="../../giella-core/dicts/scripts/gt_dictionary_XXE.css"     type="text/css"?>
<?xml-stylesheet media="screen"              title="Hierarchical view" href="../../giella-core/dicts/scripts/gt_dictionary_XXE_alt.css" type="text/css" alternate="yes" ?>
<?xml-stylesheet media="print,tv,projection" title="Dictionary view"   href="../../giella-core/dicts/scripts/gt_dictionary.css"         type="text/css"?>
<?xml-stylesheet media="print,tv,projection" title="Hierarchical view" href="../../giella-core/dicts/scripts/gt_dictionary_alt.css"     type="text/css" alternate="yes" ?>
<!DOCTYPE r PUBLIC "-//DivvunGiellatekno//DTD Dictionaries//Multilingual"
"../dtd/nobsme.dtd">
<r id="nobsme" xml:lang="nob">
  <lics xmlns:xhtml="http://www.w3.org/1999/xhtml" xml:space="preserve">
    <lic xml:lang="en">
      This code is made available under a Creative Commons Attribution license
      <a>http://creativecommons.org/licenses/by/3.0/no/deed.en</a>.

      You are free to copy, distribute and adapt the work, as long as you always give
      proper attribution using the attribution text below.

      For the full license text, see the link above.
    </lic>
    <ref>
      Work by Nils Jernsletten, Giellatekno and Divvun at UiT, and members of
      the language communities. Source code available at
      <a>https://github.com/giellalt/dict-sme-nob/</a>.
    </ref>
    <sourcenote>
      THIS TEXT IS THE ORIGINAL SOURCE CODE. This is NOT a fully styled and
      published dictionary. As such it can and will contain unfinished entries,
      unpublished entries, entries with objectionable translations, etc. If you
      find any errors or want to add more words, download the file, edit it, and
      send it back to <a>mailto:feedback@divvun.no</a> and
      <a>mailto:giellatekno@uit.no</a>. Please also note that the entries are
      not necessarily sorted, or could be wrongly sorted.
     </sourcenote>
  </lics>
    <e>

      <lg>
         <l pos="Po">rundt</l>
      </lg>
      <mg>
         <tg xml:lang="sme">
            <t pos="Pr">birra</t>
            <xg>
               <x>jorda rundt</x>
               <xt>birra máilmmi</xt>
            </xg>
         </tg>
      </mg>
   </e>
   <e>
      <lg>
         <l pos="Po">imellom</l>
      </lg>
      <mg>
         <tg xml:lang="sme">
            <t pos="Po">gaskkas</t>
            <xg>
               <x>oss imellom</x>
               <xt>munno gaskkas</xt>
            </xg>
         </tg>
      </mg>
      <mg>
         <tg xml:lang="sme">
            <re>om oss to</re>
            <t pos="Po">gaskaneame</t>
            <xg>
               <x>Vi to snakket bare norsk oss imellom.</x>
               <xt>Moai dušše dárusteimme gaskaneame.</xt>
            </xg>
         </tg>
      </mg>
      <mg>
         <tg xml:lang="sme">
            <re>om oss</re>
            <t pos="Po">gaskaneamet</t>
            <xg>
               <x>Vi snakket bare norsk oss imellom.</x>
               <xt>Mii dušše dárusteimmet gaskaneamet.</xt>
            </xg>
         </tg>
      </mg>
      <mg>
         <tg xml:lang="sme">
            <re>om dere to</re>
            <t pos="Po">gaskaneatte</t>
            <xg>
               <x>Denne delen kan dere to fritt dele dere to imellom.</x>
               <xt>Dán oasi sáhttibeahtti friddja juogadit gaskaneatte.</xt>
            </xg>
         </tg>
      </mg>
      <mg>
         <tg xml:lang="sme">
            <re>om dere</re>
            <t pos="Po">gaskaneattet</t>
            <xg>
               <x>Snakk nå samisk dere imellom!</x>
               <xt>Hállet fal sámegiela gaskaneattet!</xt>
            </xg>
         </tg>
      </mg>
      <mg>
         <tg xml:lang="sme">
            <re>om de to</re>
            <t pos="Po">gaskaneaskka</t>
            <xg>
               <x>Foreldrene kan avtale seg imellom hvor stort tilskuddet skal være.</x>
               <xt>Váhnemat sáhttiba gaskaneaskka šiehttat man stuoris doarjja galgá leat.</xt>
            </xg>
         </tg>
      </mg>
      <mg>
         <tg xml:lang="sme">
            <re>om dem</re>
            <t pos="Po">gaskaneaset</t>
            <xg>
               <x>Familiene i bygda har delt moltemyrene seg imellom.</x>
               <xt>Gili bearrašat leat juogadan luomejekkiid gaskaneaset.</xt>
            </xg>
         </tg>
      </mg>
   </e>
</r>

=== giellalt/dict-nob-sme/src/A_static_nobsme.xml
<?xml version='1.0' encoding='UTF-8'?>
<!DOCTYPE r PUBLIC "-//DivvunGiellatekno//DTD Dictionaries//Multilingual" "../dtd/nobsme.dtd">
<r id="nobsme" xml:lang="nob">
   <e>
      <lg>
         <l pos="A">sørligere</l>
      </lg>
      <mg>
         <tg xml:lang="sme" tw_id="sørligere 6a4a0b9c-028e-4888-a820-3354750db40f">
            <t pos="A">lulit</t>
            <t pos="A">máttit</t>
            <xg>
               <x>Jeg bor i det sørligere huset.</x>
               <xt>Mun orun lulit viesus.</xt>
            </xg>
            <xg>
               <x>Jeg bor i det sørligere huset.</x>
               <xt>Mun orun máttit viesus.</xt>
            </xg>
         </tg>
      </mg>
   </e>
   <e>
      <lg>
         <l pos="A">sørligst</l>
      </lg>
      <mg>
         <tg xml:lang="sme" tw_id="sørligst bef82925-a836-453d-bdf3-24d242404031">
            <t pos="A">lulimus</t>
            <t pos="A">máttimus</t>
            <xg>
               <x>Den sørligste plassen i Norge er Lindesnes.</x>
               <xt>Lulimus báiki Norggas lea Lindesnes.</xt>
            </xg>
            <xg>
               <x>Det sørligste stedet i Norge er Lindesnes.</x>
               <xt>Norgga máttimus báiki lea Lindesnes.</xt>
            </xg>
         </tg>
      </mg>
   </e>
   <e>
      <lg>
         <l pos="A">nordligere</l>
      </lg>
      <mg>
         <tg xml:lang="sme" tw_id="nordligere 172f7e0d-1ee1-4a51-bd76-385bc74feea0">
            <t pos="A">davit</t>
            <xg>
               <x>Jeg bor i det nordlige huset.</x>
               <xt>Mun orun davit viesus.</xt>
            </xg>
         </tg>
      </mg>
   </e>
   <e>
      <lg>
         <l pos="A">nordligst</l>
      </lg>
      <mg>
         <tg xml:lang="sme" tw_id="nordligst ce729b75-acc4-4a24-ab5a-1b1bc4fd4d29">
            <t pos="A">davimus</t>
            <xg>
               <x>Det nordligste stedet i Norge er Nordkapp.</x>
               <xt>Norgga davimus sadji lea Davvinjárga.</xt>
            </xg>
         </tg>
      </mg>
   </e>
   <e>
      <lg>
         <l pos="A">vestligere</l>
      </lg>
      <mg>
         <tg xml:lang="sme" tw_id="vestligere ff3ab720-4818-4657-8b66-e9ba768b2b38">
            <t pos="A">oarjjit</t>
            <xg>
               <x>Jeg bor i det vestlige huset.</x>
               <xt>Mun orun oarjjit viesus.</xt>
            </xg>
         </tg>
      </mg>
   </e>
   <e>
      <lg>
         <l pos="A">vestligst</l>
      </lg>
      <mg>
         <tg xml:lang="sme" tw_id="vestligst 28683225-dc0e-4b1b-a60f-129da4efe25a">
            <t pos="A">oarjjimus</t>
            <xg>
               <x>Den vestligste byen i Norge er Florø.</x>
               <xt>Norgga oarjjimus gávpot lea Florø.</xt>
            </xg>
         </tg>
      </mg>
   </e>
   <e>
      <lg>
         <l pos="A">østligere</l>
      </lg>
      <mg>
         <tg xml:lang="sme" tw_id="østligere da790aeb-1ae3-4eb8-861e-fbc2434f06ef">
            <t pos="A">nuorttit</t>
            <t pos="A">nuorttat</t>
            <xg>
               <x>Jeg bor i det østligere huset.</x>
               <xt>Mun orun nuorttit viesus.</xt>
            </xg>
            <xg>
               <x>Jeg bor i det østligere huset.</x>
               <xt>Mun orun nuorttat viesus.</xt>
            </xg>
         </tg>
      </mg>
   </e>
   <e>
      <lg>
         <l pos="A">østligst</l>
      </lg>
      <mg>
         <tg xml:lang="sme" tw_id="østligst 6f034bf2-acb2-45a7-9d1b-0fbbbd250bf3">
            <t pos="A">nuorttamus</t>
            <t pos="A">nuorttimus</t>
            <xg>
               <x>Den østligste byen i Norge er Vardø.</x>
               <xt>Norgga nuorttamus gávpot lea Várggát.</xt>
            </xg>
            <xg>
               <x>Den østligste byen i Norge er Vardø.</x>
               <xt>Norgga nuorttimus gávpot lea Várggát.</xt>
            </xg>
         </tg>
      </mg>
   </e>
   <e>
      <lg>
         <l pos="A">lenger ute</l>
      </lg>
      <mg>
         <tg xml:lang="sme" tw_id="lenger ute 0f735b4b-b20d-4f37-bd2e-914650d1adb0">
            <t pos="A">fávllit</t>
            <xg>
               <x>På den øya som er lengre ute er det mye fugler.</x>
               <xt>Fávllit sullos leat ollu lottit.</xt>
            </xg>
         </tg>
      </mg>
   </e>
   <e>
      <lg>
         <l pos="A">dypest</l>
      </lg>
      <mg>
         <tg xml:lang="sme" tw_id="dypest 8b3d35d8-ce58-4881-97c9-4d58d0014d09">
            <t pos="A">fávllimus</t>
            <xg>
               <x>Det dypeste stedet i elva kalles for djupål.</x>
               <xt>Fávllimus sadji jogas gohčoduvvo oallin.</xt>
            </xg>
         </tg>
      </mg>
   </e>
   <e>
      <lg>
         <l pos="A">nærmere stranda</l>
      </lg>
      <mg>
         <tg xml:lang="sme" tw_id="nærmere stranda 173559da-950b-4c70-9089-e643d37c2547">
            <t pos="Adv">gáttit</t>
            <xg>
               <x>På den øya som er nærmere stranda bruker vi å brenne bål.</x>
               <xt>Gáttit sullos mii lávet dolastallat.</xt>
            </xg>
         </tg>
      </mg>
   </e>
   <e>
      <lg>
         <l pos="A">nærmest stranda</l>
      </lg>
      <mg>
         <tg xml:lang="sme" tw_id="nærmest stranda 63fa0f55-f847-4b47-8358-edd3c26b0857">
            <t pos="A">gáttimus</t>
            <xg>
               <x>Den båten som er nærmest stranda tilhører onkelen min.</x>
               <xt>Gáttimus fanas lea mu edno fanas.</xt>
            </xg>
         </tg>
      </mg>
   </e>
   <e>
      <lg>
         <l pos="A">nærmere midten</l>
      </lg>
      <mg>
         <tg xml:lang="sme" tw_id="nærmere midten 9e68dc96-384c-4847-9d35-95f7de4e12e4">
            <t pos="A">gaskaleabbo</t>
         </tg>
      </mg>
   </e>
   <e>
      <lg>
         <l pos="A">midterste</l>
      </lg>
      <mg>
         <tg xml:lang="sme" tw_id="midterste 8352d387-81fc-463d-9bac-91594021cde9">
            <t pos="A">gaskaleamos</t>
            <xg>
               <x>Den midterste grisen er også rask.</x>
               <xt>Gaskaleamos spiidni lea maid jođán.</xt>
            </xg>
         </tg>
      </mg>
   </e>
</r>
